### ISSUE TITLE
Undefined function or variable 'datamatrix2matrix'

### ISSUE THREAD

**Issue by Stocastico** [yinqingl/nucseq_analysis#1]
Hi, I was trying to run example_bisne to see how does the algorithm work, but I always get an error because of a missing function "datamatrix2matrix". Here's Matlab output:

```
Undefined function or variable 'datamatrix2matrix'.

Error in scatter_series (line 19)
[dat, cellnames, genes, num_samples, num_genes] = datamatrix2matrix(dat_matrix);

Error in example_bisne (line 95)
scatter_series(ydata, Xj)
```

Any help is really appreciated

**Comment by yinqingl** [comment]
did you get the latest update?
